# Generated by Django 5.0.14 on 2026-08-07 08:44

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FACTORY', 'Factory'), ('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Office'), ('PARKING', 'Parking'), ('ASSEMBLY_LINE', 'Assembly Line'), ('BATTERY_ROOM', 'Battery Room'), ('DISPATCH_AREA', 'Dispatch Area'), ('CUSTOMER_SITE', 'Customer Site'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('color', models.CharField(default='#2E86DE', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex code, e.g. #FF5733', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('shape_type', models.CharField(choices=[('POLYGON', 'Polygon'), ('CIRCLE', 'Circle'), ('RECTANGLE', 'Rectangle')], max_length=10)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius_meters', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_areas', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_areas', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_areas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkAreaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area_name', models.CharField(help_text='Snapshot in case the WorkArea is later deleted', max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Boundary/shape state at the time of the action')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_area_audit_logs', to='companies.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='geofence.workarea')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workarea',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='geofence_wo_company_e8331a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workarea',
            unique_together={('branch', 'name')},
        ),
    ]
