# Generated by Django 5.0.14 on 2026-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttiming',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='End of the daily lunch/meal break, if any', null=True),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Start of the daily lunch/meal break, if any', null=True),
        ),
    ]
