# Generated by Django 5.0.14 on 2026-08-08 02:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('last_battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gps_enabled', models.BooleanField(default=True)),
                ('network_connected', models.BooleanField(default=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_live_statuses', to='companies.company')),
                ('current_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_currently_here', to='geofence.workarea')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_status', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee live statuses',
                'indexes': [models.Index(fields=['company', 'branch', 'last_ping_at'], name='tracking_em_company_a46832_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('gps_enabled', models.BooleanField(default=True)),
                ('network_connected', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='employees.employee')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='geofence.workarea')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['employee', '-recorded_at'], name='tracking_lo_employe_e18a74_idx'), models.Index(fields=['company', '-recorded_at'], name='tracking_lo_company_25b15d_idx')],
            },
        ),
    ]
