# Generated by Django 5.0.14 on 2026-08-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelivestatus',
            options={'ordering': ['-last_ping_at'], 'verbose_name_plural': 'Employee live statuses'},
        ),
    ]
