# Generated by Django 5.0.14 on 2026-08-08 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SHIFT_START', 'Shift Started'), ('SHIFT_END', 'Shift Ended'), ('GEOFENCE_ENTER', 'Entered Work Area'), ('GEOFENCE_EXIT', 'Exited Work Area'), ('GPS_DISABLED', 'GPS Disabled'), ('INTERNET_DISCONNECTED', 'Internet Disconnected'), ('ABSENT', 'Marked Absent'), ('LATE_ARRIVAL', 'Late Arrival')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('delivery_status', models.CharField(choices=[('SENT', 'Sent to at least one device'), ('NO_DEVICE', 'No active device registered'), ('FAILED', 'Delivery failed')], default='NO_DEVICE', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
