# Generated by Django 5.0.14 on 2026-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIFT_START', 'Shift Started'), ('SHIFT_END', 'Shift Ended'), ('GEOFENCE_ENTER', 'Entered Work Area'), ('GEOFENCE_EXIT', 'Exited Work Area'), ('GPS_DISABLED', 'GPS Disabled'), ('INTERNET_DISCONNECTED', 'Internet Disconnected'), ('ABSENT', 'Marked Absent'), ('LATE_ARRIVAL', 'Late Arrival'), ('TRANSFER_REQUESTED', 'Transfer Requested'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('TRANSFER_REJECTED', 'Transfer Rejected'), ('OUTDOOR_DUTY_REQUESTED', 'Outdoor Duty Requested'), ('OUTDOOR_DUTY_APPROVED', 'Outdoor Duty Approved'), ('OUTDOOR_DUTY_REJECTED', 'Outdoor Duty Rejected')], max_length=25),
        ),
    ]
