# Generated by Django 5.0.14 on 2026-08-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_source', models.CharField(choices=[('MANUAL', 'Manual (Start/End Shift)'), ('AUTO_GEOFENCE', 'Automatic (Geofence Entry/Exit)'), ('SYSTEM', 'System (e.g. end-of-day absentee marking)')], default='MANUAL', max_length=20)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_source', models.CharField(choices=[('MANUAL', 'Manual (Start/End Shift)'), ('AUTO_GEOFENCE', 'Automatic (Geofence Entry/Exit)'), ('SYSTEM', 'System (e.g. end-of-day absentee marking)')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('late_by_minutes', models.PositiveIntegerField(default=0)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('early_exit_by_minutes', models.PositiveIntegerField(default=0)),
                ('working_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.branch')),
                ('check_in_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='geofence.workarea')),
                ('check_out_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='geofence.workarea')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.shifttiming')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date', 'status'], name='attendance__company_f24fc4_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
