# Generated by Django 5.0.14 on 2026-09-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_is_outdoor_duty_outdoordutyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='total_break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BreakPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['attendance_record', 'ended_at'], name='attendance__attenda_458876_idx')],
            },
        ),
    ]
